export enum ActionTypes { 
    SET_PLAYSTATION_GAMES_DATA = "SET_PLAYSTATION_GAMES_DATA",
    CHANGE_PLAYSTATION_PLATFORM = "CHANGE_PLAYSTATION_PLATFORM",
    CHANGE_PLAYSTATION_PUBLISHER = "CHANGE_PLAYSTATION_PUBLISHER",
    CHANGE_PLAYSTATION_GENRE = "CHANGE_PLAYSTATION_GENRE",
    RESET_PLAYSTATION_FILTERS = "RESET_PLAYSTATION_FILTERS"
 }


export enum PayloadTypes{}

export interface Action {
type:ActionTypes;
payload?: any;
}